name: Deploy to Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Trigger Deploy to Site
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zou8944/my-blog-hexo/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"unit\": false, \"integration\": true}}"